#!/bin/bash

# Kiwiz - Kinde Authentication Setup Script
# This script helps you set up the environment variables for Kinde authentication

echo "🎨 Kiwiz - AI Coloring & Tracing App Setup"
echo "=========================================="
echo ""

# Check if .env.local already exists
if [ -f ".env.local" ]; then
    echo "⚠️  .env.local already exists!"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Setup cancelled."
        exit 1
    fi
fi

echo "📝 Setting up environment variables..."
echo ""

# Get Kinde configuration from user
echo "Please provide your Kinde configuration:"
echo ""

read -p "Kinde Client ID: " KINDE_CLIENT_ID
read -p "Kinde Client Secret: " KINDE_CLIENT_SECRET
read -p "Kinde Issuer URL (e.g., https://your-subdomain.kinde.com): " KINDE_ISSUER_URL
read -p "Site URL (default: http://localhost:3000): " KINDE_SITE_URL
read -p "Post Login Redirect URL (default: http://localhost:3000/dashboard): " KINDE_POST_LOGIN_REDIRECT_URL

# Set defaults if empty
KINDE_SITE_URL=${KINDE_SITE_URL:-"http://localhost:3000"}
KINDE_POST_LOGIN_REDIRECT_URL=${KINDE_POST_LOGIN_REDIRECT_URL:-"http://localhost:3000/dashboard"}

# Create .env.local file
cat > .env.local << EOF
# Kinde Authentication Configuration
# Generated by setup script on $(date)

KINDE_CLIENT_ID=${KINDE_CLIENT_ID}
KINDE_CLIENT_SECRET=${KINDE_CLIENT_SECRET}
KINDE_ISSUER_URL=${KINDE_ISSUER_URL}
KINDE_SITE_URL=${KINDE_SITE_URL}
KINDE_POST_LOGOUT_REDIRECT_URL=${KINDE_SITE_URL}
KINDE_POST_LOGIN_REDIRECT_URL=${KINDE_POST_LOGIN_REDIRECT_URL}

# Optional: Add audience for API access
# KINDE_AUDIENCE=<your-api>

# Optional: Debug mode
# KINDE_DEBUG_MODE=true
EOF

echo ""
echo "✅ Environment variables created successfully!"
echo ""
echo "📋 Next steps:"
echo "1. Make sure your Kinde application is configured with these callback URLs:"
echo "   - Allowed callback URLs: ${KINDE_SITE_URL}/api/auth/kinde_callback"
echo "   - Allowed logout redirect URLs: ${KINDE_SITE_URL}"
echo "   - Allowed login redirect URLs: ${KINDE_POST_LOGIN_REDIRECT_URL}"
echo ""
echo "2. Start the development server:"
echo "   pnpm dev"
echo ""
echo "3. Open your browser to: ${KINDE_SITE_URL}"
echo ""
echo "🎉 Happy coding!"
